/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Hassan
 */
public class addFlight extends javax.swing.JFrame {
Connection con;
    SimpleDateFormat sdf;
    ResultSet rs;
    Statement st;
    int fid=0;
    DateFormat timeFormat;
    public addFlight() {
        initComponents();
        
        try{Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ars_data","root","root");
            jfdate.setDate(Calendar.getInstance().getTime());
            sdf= new SimpleDateFormat("yyyy-MM-dd");
            timeFormat = new SimpleDateFormat("hh:mm:ss");
            jPanel6.setBackground(new Color(0,0,0,0));
            getAircraftsandSectors();
            setfid();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    public void setfid()
    {
        try {
            String que="select count(flightID) from flights";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery(que);
                if(rs.next()) {
                    int count=rs.getInt(1);
                    fid=++count;
                    jfid.setText(Integer.toString(fid));
                }
        } catch (Exception e) {
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        flights = new javax.swing.JLabel();
        contactUs = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logout = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        notifications = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jfid = new javax.swing.JTextField();
        jexs = new javax.swing.JTextField();
        jreset = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jadd = new javax.swing.JButton();
        jfno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jecs = new javax.swing.JTextField();
        jbcs = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jaircraft = new javax.swing.JComboBox<>();
        jairline = new javax.swing.JComboBox<>();
        jstatus = new javax.swing.JComboBox<>();
        jfdate = new com.toedter.calendar.JDateChooser();
        jsector = new javax.swing.JComboBox<>();
        jarrt = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jdept = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel23 = new javax.swing.JLabel();

        jLabel10.setText("Flight");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Flights");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-530, -150, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1709, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flights.setBackground(new java.awt.Color(255, 255, 255));
        flights.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        flights.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flights.setText("Flights");
        flights.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flightsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flightsMouseExited(evt);
            }
        });
        jPanel9.add(flights, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 121, -1));

        contactUs.setBackground(new java.awt.Color(255, 255, 255));
        contactUs.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contactUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactUs.setText("Contact Us");
        contactUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactUsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactUsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactUsMouseExited(evt);
            }
        });
        jPanel9.add(contactUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 128, -1));

        jLabel12.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Airline Reservation System");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel9.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 1703, 10));

        logout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel9.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 100, -1));

        jPanel5.setLayout(null);

        jLabel13.setText("hfghtdfgkhvjhlbuhkvhbhjghjkbi");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(414, 1070, 148, 14);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img1.jpg"))); // NOI18N
        jPanel5.add(jLabel14);
        jLabel14.setBounds(200, 73, 1400, 933);

        jPanel9.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 1703, -1));

        notifications.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        notifications.setText("Notifications");
        notifications.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notifications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificationsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notificationsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notificationsMouseExited(evt);
            }
        });
        jPanel9.add(notifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 130, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 1420, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Flight", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Flight Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Flight Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Economy class seats available");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Departure Time");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Arrival Time");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, -1));

        jBack.setText("Go Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 96, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Sector");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 60, 20));

        jfid.setEditable(false);
        jfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfidActionPerformed(evt);
            }
        });
        jPanel1.add(jfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 60, -1));
        jPanel1.add(jexs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 230, -1));

        jreset.setBackground(new java.awt.Color(204, 204, 204));
        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });
        jPanel1.add(jreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 90, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Airline");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 70, -1));

        jadd.setText("Add");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });
        jPanel1.add(jadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 96, 30));

        jfno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfnoActionPerformed(evt);
            }
        });
        jPanel1.add(jfno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Flight Number");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, 20));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Business class seats available");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Executive class seats available");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, -1));

        jecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jecsActionPerformed(evt);
            }
        });
        jPanel1.add(jecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, -1));
        jPanel1.add(jbcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 230, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Aircraft");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, -1));

        jPanel1.add(jaircraft, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 90, -1));

        jPanel1.add(jairline, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, -1));

        jstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confirmed", "Cancelled", "Delayed" }));
        jstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstatusActionPerformed(evt);
            }
        });
        jPanel1.add(jstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 90, -1));
        jPanel1.add(jfdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 110, 230, -1));

        jsector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsectorActionPerformed(evt);
            }
        });
        jPanel1.add(jsector, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 90, -1));
        jPanel1.add(jarrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 110, -1));
        jPanel1.add(jdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, -1));

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 470, 530));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 800, 550));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img3.jpg"))); // NOI18N
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1400, 690));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flightsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsMouseClicked

    }//GEN-LAST:event_flightsMouseClicked

    private void flightsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsMouseEntered
        // TODO add your handling code here:

        Font font = flights.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        flights.setFont(font.deriveFont(attributes));
        flights.setForeground(Color.pink);
    }//GEN-LAST:event_flightsMouseEntered

    private void flightsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightsMouseExited
        // TODO add your handling code here:
        Font font = flights.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        flights.setFont(font.deriveFont(attributes));
        flights.setForeground(Color.BLACK);
    }//GEN-LAST:event_flightsMouseExited

    private void contactUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUsMouseClicked

    }//GEN-LAST:event_contactUsMouseClicked

    private void contactUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUsMouseEntered
        // TODO add your handling code here:

        Font font = contactUs.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        contactUs.setFont(font.deriveFont(attributes));
        contactUs.setForeground(Color.pink);
    }//GEN-LAST:event_contactUsMouseEntered

    private void contactUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUsMouseExited
        // TODO add your handling code here:

        Font font = contactUs.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        contactUs.setFont(font.deriveFont(attributes));
        contactUs.setForeground(Color.BLACK);
    }//GEN-LAST:event_contactUsMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        LoginPage r = new LoginPage();
        r.setVisible(true);
        r.pack();
        r.setLocationRelativeTo(null);
        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        Font font = logout.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        logout.setFont(font.deriveFont(attributes));
        logout.setForeground(Color.white);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        Font font = logout.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, -1);
        logout.setFont(font.deriveFont(attributes));
        logout.setForeground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void notificationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationsMouseClicked
        // TODO add your handling code here:
        //        Notifications r = new Notifications();
        //        r.setVisible(true);
        //        r.pack();
        //        r.setLocationRelativeTo(null);
        //        r.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //        this.dispose();
    }//GEN-LAST:event_notificationsMouseClicked

    private void notificationsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationsMouseEntered
        // TODO add your handling code here:
        //        Font font = inbox.getFont();
        //        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        //        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        //        inbox.setFont(font.deriveFont(attributes));
        //        inbox.setForeground(Color.pink);
    }//GEN-LAST:event_notificationsMouseEntered

    private void notificationsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificationsMouseExited
        // TODO add your handling code here:
        //        Font font = inbox.getFont();
        //        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        //        attributes.put(TextAttribute.UNDERLINE, -1);
        //        inbox.setFont(font.deriveFont(attributes));
        //        inbox.setForeground(Color.black);
    }//GEN-LAST:event_notificationsMouseExited

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        viewFlights updt=new viewFlights();
        updt.setVisible(true);
        updt.pack();
        updt.setLocationRelativeTo(null);
        updt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jBackActionPerformed

    private void jfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfidActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
    try {
        jfid.setText(Integer.toString(fid));
        jfno.setText(null);
        jfdate.setDate(null);
        jbcs.setText(null);
        jexs.setText(null);
        jecs.setText(null);
        jdept.setTime(timeFormat.parse("00:00:00"));
        jarrt.setTime(timeFormat.parse("00:00:00"));
        jaircraft.setSelectedItem(null);
        jsector.setSelectedItem(null);
        jstatus.setSelectedItem(null);
        jairline.setSelectedItem(null);
    } catch (ParseException ex) {
        Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jresetActionPerformed
     public void getAircraftsandSectors()
    {
        String query1="select aircraftNo from aircraft";
        String query2="select sectorID from sector";
        String query3="select airlineCode from airline";
        try{ 
                st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery(query1);
                boolean empty = true;
                while (rs.next()) {
                    empty = false;
                    int i=1;
                    jaircraft.addItem(rs.getString(i));
                    i++;
                }
                System.out.println(jaircraft.getSelectedItem().toString());
                rs = st.executeQuery(query2);
                try{ 
                st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery(query2);
                boolean emp = true;
                while (rs.next()) {
                    empty = false;
                    int i=1;
                    jsector.addItem(rs.getString(i));
                    i++;
                }
                }
                catch (SQLException ex) {
                    Logger.getLogger(updateFlight.class.getName()).log(Level.SEVERE, null, ex);
                }
                try{ 
                st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery(query3);
                boolean emp = true;
                while (rs.next()) {
                    empty = false;
                    int i=1;
                    jairline.addItem(rs.getString(i));
                    i++; }
                    }
           catch (SQLException ex) {
        Logger.getLogger(updateFlight.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    catch (SQLException ex) {
        Logger.getLogger(updateFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        // TODO add your handling code here:
        try{
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            if(jfno.getText().equals("")||sdf.format(jfdate.getDate()).equals(null)||jbcs.getText().equals("")||
                    jexs.getText().equals("")||jecs.getText().equals("")||jdept.getFormatedTime().equals("00:00:00")||
                    jarrt.getFormatedTime().equals("00:00:00")||jaircraft.getSelectedItem().toString().equals(null)||
                    jsector.getSelectedItem().toString().equals(null)||
                    jairline.getSelectedItem().toString().equals(null)||jstatus.getSelectedItem().toString().equals(null))
            {
                JOptionPane.showMessageDialog(this,"Enter complete details");
            }
            else{
                String query = "INSERT INTO `flights`(flightno,flightdate,bcsavailable,xcsavailable,ecsavailable,"
                    + "deptime,arrtime,aircrafttypeID,sectorID,airlineCode,status)"
                    + " VALUES ('"+jfno.getText()+"','"+sdf.format(jfdate.getDate())+"','"+jbcs.getText()+"',"
                    + "'"+jexs.getText()+"','"+jecs.getText()+"','"+jdept.getFormatedTime()+"',"
                    + "'"+jarrt.getFormatedTime()+"','"+jaircraft.getSelectedItem().toString()+"',"
                    + "'"+jsector.getSelectedItem().toString()+"','"+jairline.getSelectedItem().toString()+"',"
                    + "'"+jstatus.getSelectedItem().toString()+"')";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Information Updated Successfully");
            String que="select flightID from flights where flightno='"+jfno.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rs = st.executeQuery(que);
                if(rs.next()) {
                    fid=rs.getInt(1);
                }
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this,"Failed: " + ex.getMessage());

        }
    }//GEN-LAST:event_jaddActionPerformed

    private void jfnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfnoActionPerformed

    private void jecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jecsActionPerformed

    private void jstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstatusActionPerformed

    private void jsectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactUs;
    private javax.swing.JLabel flights;
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jadd;
    private javax.swing.JComboBox<String> jaircraft;
    private javax.swing.JComboBox<String> jairline;
    private lu.tudor.santec.jtimechooser.JTimeChooser jarrt;
    private javax.swing.JTextField jbcs;
    private lu.tudor.santec.jtimechooser.JTimeChooser jdept;
    private javax.swing.JTextField jecs;
    private javax.swing.JTextField jexs;
    private com.toedter.calendar.JDateChooser jfdate;
    private javax.swing.JTextField jfid;
    private javax.swing.JTextField jfno;
    private javax.swing.JButton jreset;
    private javax.swing.JComboBox<String> jsector;
    private javax.swing.JComboBox<String> jstatus;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel notifications;
    // End of variables declaration//GEN-END:variables
}
