package gui;
import ars.admin;
import java.awt.*;
import java.awt.font.TextAttribute;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.JFrame;

public class manageAdmin extends javax.swing.JFrame {
Connection con;
    SimpleDateFormat sdf;
    ResultSet rs;
    Statement st;
String fname = "", lname="",username="",email="",city="",password="";
    int adminid=0;
    long phoneno=0;
    public manageAdmin() {
        initComponents();
         try{Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ars_data","root","root");
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        displaydata();
    }
    public void displaydata()
    { 
        jadminid.setText(Integer.toString(admin.adminid));
        jphoneno.setText(admin.phoneno);
        jfname.setText(admin.fname);
        jlname.setText(admin.lname);
        jemail.setText(admin.email);
        jpassword.setText(admin.password);
        jcity.setText(admin.city);
        jadminname.setText(admin.adminname);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBack = new javax.swing.JButton();
        jadminid = new javax.swing.JTextField();
        jfname = new javax.swing.JTextField();
        jadminname = new javax.swing.JTextField();
        jreset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jupdate = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlname = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jphoneno = new javax.swing.JTextField();
        jcity = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Admin ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("First name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 90, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Phone no:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 254, 90, 10));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("City");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 20));

        jBack.setText("Go Back");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 96, 30));

        jadminid.setEditable(false);
        jadminid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadminidActionPerformed(evt);
            }
        });
        jPanel1.add(jadminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, -1));

        jfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfnameActionPerformed(evt);
            }
        });
        jPanel1.add(jfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, -1));
        jPanel1.add(jadminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, -1));

        jreset.setBackground(new java.awt.Color(204, 204, 204));
        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });
        jPanel1.add(jreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 90, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });
        jPanel1.add(jupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 96, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Last name");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 144, 90, 20));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Username");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, 90, 30));
        jPanel1.add(jlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 190, -1));

        jemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailActionPerformed(evt);
            }
        });
        jPanel1.add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, -1));

        jphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jphonenoActionPerformed(evt);
            }
        });
        jPanel1.add(jphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 190, 20));

        jcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcityActionPerformed(evt);
            }
        });
        jPanel1.add(jcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, -1));
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        adminConsole updt=new adminConsole();
        updt.setVisible(true);
        updt.pack();
        updt.setLocationRelativeTo(null);
        updt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jBackActionPerformed

    private void jadminidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadminidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadminidActionPerformed

    private void jfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfnameActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
        displaydata();
    }//GEN-LAST:event_jresetActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
        // TODO add your handling code here:
        try{
            String query = "update staff set fName = '"+jfname.getText()+"',lName= '"+jlname.getText()+"',"
            + " email = '"+jemail.getText()+"',phoneNo='"+jphoneno.getText()+"',"
            + " city = '"+jcity.getText()+"', password='"+jpassword.getText()+"',"
            + "adminname='"+jadminname.getText()+"' where staffId='"+jadminid.getText()+"'";
            st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            st.executeUpdate(query);

            JOptionPane.showMessageDialog(this,"Information Updated Successfully");
            setAdmin();
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this,"Failed: " + ex.getMessage());
            System.out.println("error: "+ex.getMessage());

        }
    }//GEN-LAST:event_jupdateActionPerformed
    public void setAdmin()
    {
        admin.adminname=jadminname.getText();
        admin.password=jpassword.getText();
        admin.adminid=Integer.parseInt(jadminid.getText());
        admin.fname=jfname.getText();
        admin.lname=jlname.getText();
        admin.phoneno=jphoneno.getText();
        admin.city=jcity.getText();
        admin.email=jemail.getText();
    }
    private void jemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailActionPerformed

    private void jphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jphonenoActionPerformed

    private void jcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBack;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jadminid;
    private javax.swing.JTextField jadminname;
    private javax.swing.JTextField jcity;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jfname;
    private javax.swing.JTextField jlname;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jphoneno;
    private javax.swing.JButton jreset;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables
}
